services:
  mysql-db-cl:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: coderslab
      MYSQL_DATABASE: bookStore
      MYSQL_USER: arek
      MYSQL_PASSWORD: coderslab
    ports:
      - '6306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
